services:
  - type: web
    name: pdf-downloader-production
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
